# Generated by Django 3.2.8 on 2022-03-03 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rights_transactions', '0002_alter_rightstransaction_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rightstransaction',
            name='color',
        ),
    ]
