# Generated by Django 5.1 on 2024-08-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "rights_transactions",
            "0003_alter_rightstransaction_gross_price_per_share_currency_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="rightstransaction",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
