# Generated by Django 5.1 on 2024-08-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rights_transactions", "0004_alter_rightstransaction_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rightstransaction",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
