# Generated by Django 3.2.8 on 2021-12-03 10:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock_prices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockprice',
            name='company',
        ),
        migrations.RemoveField(
            model_name='stockprice',
            name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='stockprice',
            name='user',
        ),
        migrations.AddField(
            model_name='stockprice',
            name='company_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockprice',
            name='ticker',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
