# Generated by Django 3.2.8 on 2021-12-03 14:35

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stock_prices', '0002_auto_20211203_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprice',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=19, max_digits=29),
        ),
    ]
