# Generated by Django 3.2.8 on 2022-05-27 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_prices', '0002_alter_stockprice_price_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockprice',
            name='company_name',
        ),
    ]
