# Generated by Django 3.2.8 on 2021-12-03 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_prices', '0003_alter_stockprice_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockprice',
            unique_together={('ticker', 'transaction_date')},
        ),
    ]
