# Generated by Django 3.2.8 on 2022-01-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage',
            name='message_text',
            field=models.CharField(max_length=400),
        ),
    ]
