# Generated by Django 3.2.18 on 2023-03-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_messages', '0002_alter_logmessage_message_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logmessage',
            options={'verbose_name': 'Log Message', 'verbose_name_plural': 'Log Messages'},
        ),
        migrations.RemoveField(
            model_name='logmessage',
            name='user',
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
