# Generated by Django 3.2.8 on 2022-01-07 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='market',
            options={'ordering': ['name']},
        ),
    ]
