# Generated by Django 3.2.13 on 2022-11-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0005_auto_20220815_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
