# Generated by Django 3.2.8 on 2021-11-26 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20211126_1104'),
        ('portfolios', '0002_alter_portfolio_base_currency'),
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
