# Generated by Django 3.2.18 on 2023-03-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_alter_currency_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['code'], 'verbose_name': 'Currency', 'verbose_name_plural': 'currencies'},
        ),
        migrations.AlterField(
            model_name='currency',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
