# Generated by Django 3.2.8 on 2021-12-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_from', models.CharField(max_length=200)),
                ('exchange_to', models.CharField(max_length=200)),
                ('exchange_rate', models.DecimalField(max_digits=12, decimal_places=3)),
                ('exchange_date', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('exchange_from', 'exchange_to', 'exchange_date')},
            },
        ),
    ]
