# Generated by Django 3.2.8 on 2021-11-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangerate',
            old_name='exchange_name',
            new_name='exchange_from',
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='exchange_to',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
