# Generated by Django 3.2.8 on 2021-11-27 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rates', '0002_auto_20211127_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangerate',
            name='user',
        ),
    ]
