# Generated by Django 3.2.8 on 2021-11-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rates', '0004_alter_exchangerate_exchange_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=19, max_digits=29),
        ),
    ]
