# Generated by Django 3.2.8 on 2021-12-03 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rates', '0005_alter_exchangerate_exchange_rate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('exchange_from', 'exchange_to', 'exchange_date')},
        ),
    ]
