# Generated by Django 5.0.7 on 2024-08-11 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0002_usersettings_backend_hostname_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersettings",
            name="backend_hostname",
        ),
    ]
