# Generated by Django 5.0.7 on 2024-08-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0003_remove_usersettings_backend_hostname"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="display_welcome",
            field=models.BooleanField(default=True),
        ),
    ]
