# Generated by Django 3.2.8 on 2022-05-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_usersettings_allow_fetch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='company_display_mode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='company_sort_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='main_portfolio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='portfolio_display_mode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='portfolio_sort_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
