# Generated by Django 3.2.8 on 2022-01-08 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0002_auto_20220107_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='super_sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sectors', to='sectors.supersector'),
        ),
        migrations.AlterField(
            model_name='supersector',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
