# Generated by Django 3.2.13 on 2022-08-16 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0003_auto_20220108_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='color',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='user',
        ),
        migrations.RemoveField(
            model_name='supersector',
            name='color',
        ),
        migrations.RemoveField(
            model_name='supersector',
            name='user',
        ),
    ]
