# Generated by Django 3.2.18 on 2023-03-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0004_auto_20220816_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supersector',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
