# Generated by Django 3.2.8 on 2021-11-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='currency',
        ),
        migrations.AddField(
            model_name='company',
            name='base_currency',
            field=models.CharField(default='EUR', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='dividends_currency',
            field=models.CharField(max_length=50),
        ),
    ]
