# Generated by Django 3.2.8 on 2021-12-20 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='logo',
        ),
    ]
