# Generated by Django 3.2.8 on 2021-12-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares_transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharestransaction',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
