# Generated by Django 5.1 on 2024-08-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shares_transactions", "0003_alter_sharestransaction_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sharestransaction",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
