# Generated by Django 4.1.7 on 2023-03-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shares_transactions", "0005_auto_20230306_1302"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sharestransaction",
            name="count",
            field=models.IntegerField(default=0),
        ),
    ]
