# Generated by Django 3.2.8 on 2022-01-07 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_alter_company_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyStatsForYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('shares_count', models.IntegerField()),
                ('invested', models.DecimalField(decimal_places=3, max_digits=12)),
                ('dividends', models.DecimalField(decimal_places=3, max_digits=12)),
                ('portfolio_currency', models.CharField(max_length=200)),
                ('accumulated_investment', models.DecimalField(decimal_places=3, max_digits=12)),
                ('accumulated_dividends', models.DecimalField(decimal_places=3, max_digits=12)),
                ('portfolio_value', models.DecimalField(decimal_places=3, max_digits=12)),
                ('portfolio_value_is_down', models.BooleanField()),
                ('return_value', models.DecimalField(decimal_places=3, max_digits=12)),
                ('return_percent', models.DecimalField(decimal_places=3, max_digits=12)),
                ('return_with_dividends', models.DecimalField(decimal_places=3, max_digits=12)),
                ('return_with_dividends_percent', models.DecimalField(decimal_places=3, max_digits=12)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='companies.company')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('year', 'company')},
            },
        ),
    ]
