# Generated by Django 3.2.8 on 2022-01-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystatsforyear',
            name='stock_price_currency',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companystatsforyear',
            name='stock_price_transaction_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='companystatsforyear',
            name='stock_price_value',
            field=models.DecimalField(decimal_places=3, max_digits=12, null=True),
        ),
    ]
