# Generated by Django 3.2.8 on 2022-01-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20220107_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystatsforyear',
            name='dividends_yield',
            field=models.DecimalField(decimal_places=3, max_digits=12, null=True),
        ),
    ]
