# Generated by Django 3.2.18 on 2023-03-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20220815_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companystatsforyear',
            options={'verbose_name': 'Company Stats', 'verbose_name_plural': 'Companies Stats'},
        ),
        migrations.AlterModelOptions(
            name='portfoliostatsforyear',
            options={'verbose_name': 'Portfolio Stats', 'verbose_name_plural': 'Portfolios Stats'},
        ),
        migrations.RemoveField(
            model_name='companystatsforyear',
            name='user',
        ),
        migrations.RemoveField(
            model_name='portfoliostatsforyear',
            name='user',
        ),
        migrations.AlterField(
            model_name='companystatsforyear',
            name='stock_price_currency',
            field=models.CharField(default='', max_length=200),
        ),
    ]
