# Generated by Django 3.2.8 on 2021-11-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='base_currency',
            field=models.CharField(max_length=50),
        ),
    ]
