# Generated by Django 3.2.8 on 2021-11-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_alter_portfolio_base_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='country_code',
            field=models.CharField(default='EUR', max_length=200),
            preserve_default=False,
        ),
    ]
