# Generated by Django 3.2.13 on 2022-08-12 07:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_markets_indexes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmarketindexyear',
            name='return_percentage',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12),
        ),
    ]
